const express = require('express');
const bodyparser = require('body-parser');
const morgan = require('morgan');
const cors = require('cors');
const loginregister = require('./routes/registerandloginroute');
const homepage = require('./routes/homepageroute');
const saveuserdata = require('./routes/saveuserregistrationroute');
const checkuserexists = require('./routes/checkifuserexistsroute');
const loadData = require('./routes/loadQuizDataOnLoginRoute');
const loadDataBasedOnDifficulty = require('./routes/loadQuizDataOndifficultyRoute');
const loadaltdata = require('./routes/loadQuizDataOnaltchoiceroute');
const loadSection = require('./routes/getsectionroute');
const loadquizdata = require('./routes/loadquizdataroute');
const loadquizquestions = require('./routes/loadquestionsroute');
const checkcorrectanswer = require('./routes/checkanswersroute');
const loadresults = require('./routes/resultpageroute');
const displayresults = require('./routes/loadresultroute');
const saveuserresults = require('./routes/saveuserresultsroute');
const storedresults = require('./routes/displaystoredresultsroute');
const loadstoredresults = require('./routes/loadstoredresultsroute');
const deleteresult = require('./routes/deletequizresultsroute');
const port = process.env.PORT || 4000;
const app = express();
app.listen(port, () => {
    console.log(`server running on port ${port}`);
});
app.use(cors());
app.use(bodyparser.urlencoded({ extended: true }));
app.use(express.json());
app.use(morgan('tiny'));
app.use('/', loginregister);
app.use('/homepage', homepage);
app.use('/saveuser', saveuserdata);
app.use('/checkuserexists', checkuserexists);
app.use('/loadData', loadData);
app.use('/loadqdataondif', loadDataBasedOnDifficulty);
app.use('/loaduseralternativechoice', loadaltdata);
app.use('/getsection', loadSection);
app.use('/quizitup', loadquizdata);
app.use('/getquestions', loadquizquestions);
app.use('/checkanswers', checkcorrectanswer);
app.use('/result', loadresults);
app.use('/loadresults', displayresults);
app.use('/saveuserresults', saveuserresults);
app.use('/storedresults', storedresults);
app.use('/loadstoredresults', loadstoredresults);
app.use('/deleteresult', deleteresult);